### ISSUE TITLE
qemu-img dependency

### ISSUE THREAD

**Issue by swsyes** [kata-containers/documentation#10]
In the "Create an image" section,
in the "Build the image" sub section
I hit the "qemu-img" not installed dependency. It probably needs to be called out upfront in the "Assumptions" section up-top.

**Comment by jodh-intel** [comment]
Hi @swsyes - the problem is, you don't need that command *iff* you use osbuilder with Docker (which is generally going to be easier as all deps are handled for you).

I've added a note to https://github.com/kata-containers/documentation/wiki/Developer-Guide#build-the-image. Let me know if you think that's sufficient though.

**Comment by swsyes** [comment]
Can be closed now...thanks

**Comment by jodh-intel** [comment]
@swsyes - great. Thanks.
