### ISSUE TITLE
Dev-guide: Use a script for Installing guest kernel images. 

### ISSUE THREAD

**Issue by nitkon** [kata-containers/documentation#128]
Currently, the [Install guest kernel images](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#install-guest-kernel-images) section in the dev-guide has manual steps to build and install the guest kernel image. Replace it with a step to invoke the script which will, in turn, have these steps. 

Currently, the agreed approach(cc: @devimc ) is to place this script in runtime/scripts/install_guest_kernel.sh and update dev guide to invoke it. ( sh $GOPATH/src/github.com/kata-containers/runtime/scripts/install_guest_kernel.sh )

**Comment by jodh-intel** [comment]
I'm not sure we want to (or even can) move that script to the runtime repo given the way our CI works: when a PR for a component is tested, we always check out the https://github.com/kata-containers/tests repo to pull in the CI scripts. Moving the script to runtime would change that logic.

I agree that since that document cannot be fully "executed" by https://github.com/kata-containers/tests/blob/master/.ci/kata-doc-to-script.sh (due to the conditional nature of the document - do you want to use an image? Or an initrd?), it makes sense to point users at a script to run instead. That ensures we'll get fast feedback if the script breaks since the CI and users will be using it. It's also simpler from the users perspective. We will need to make sure this script is "safe" to run on a devbox (see https://github.com/kata-containers/tests#developer-mode) since CI scripts will assume they can do "anything" to a system including, but not limited to, reformatting the harddisk and eating your cat.

As such, users must *NOT* set the `CI` environment variable when running CI scripts to avoid potential disaster.

`<random-thoughts>`

On a more general note:

- we might want to look at replacing all the code snippets in the dev guide with references to the appropriate CI scripts at some point?

- we might want to instead, retain the `install_*.sh` scripts in https://github.com/kata-containers/tests/tree/master/.ci but make them stubs that call into https://github.com/kata-containers/tests/blob/master/cmd/kata-manager/kata-manager.sh. That script is currently limited to installing the packaged version of kata and configuring the runtime. But we could expand the scope so that there is a `--source` option or similar to build from source instead?

What's your view @chavafg?

`</random-thoughts>`

**Comment by nitkon** [comment]
@jodh-intel : Thanks for your analysis and review. However, I was thinking from the point of view of having [Install guest kernel images](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#install-guest-kernel-images) for ppc64le as well. 

Given what you have said, then the option we can go with as of now would be something like this?

if [ $kernel_arch == ppc64le ] ; then curl -L https://raw.githubusercontent.com/kata-containers/packaging/master/kernel/configs/ppc64le_kata_kvm_4.14.x -o .config; else curl -L https://raw.githubusercontent.com/kata-containers/packaging/master/kernel/configs/x86_kata_kvm_4.14.x -o .config;fi


Similarly for the rest of the arch specific commands that come under [Install guest kernel images](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#install-guest-kernel-images) ?

**Comment by jodh-intel** [comment]
On the topic of architectures, https://github.com/kata-containers/tests/blob/master/.ci/install_kata_kernel.sh does handle non-`x86_64` currently by building those architectures from source.

However, going forward we really need to be able to not only run the CI's for all architectures, but [package](https://github.com/kata-containers/packaging) for them too.

**Comment by chavafg** [comment]
@nitkon is this still relevant?

**Comment by amshinde** [comment]
We have a script in place now to build kernel. Looks like this has gotten stale.
Closing this. @nitkon Please reopen if sill relevant adding in new details.
