### ISSUE TITLE
add basic vpp use case details

### ISSUE THREAD

**Issue by egernst** [kata-containers/documentation#209]

**Comment by junxiaocne** [comment]
@egernst Hi Eric, is there any reason that only vpp use case was added but not ovs-dpdk? or kata team prefers vpp in vhost-user use case?

**Comment by egernst** [comment]
Hey @junxiaocne - no - it was the first one that was ready (CNM plugin), and was straight forward to setup.  Would be happy to have similar document for OVS / OVS-DPDK!

**Comment by junxiaocne** [comment]
@egernst Thanks Eric for the info.
A couple of reasons why I was asking:
- Because vhost-user interface (of both OVS-DPDK and VPP) has lower throughput for TCP workload than OVS kernel datapath, and I assume Kata Container's main target applications would be TCP based instead of VNF like applications, so that might be a concern. (here is a reference from redhat https://access.redhat.com/solutions/2971871)
- We (CloudNetEngine) have virtual switch solutions to support TCP based workloads over vhost-user interface to get both high throughput and low CPU consumption, thus try to find a way to integrate with kata container to boost network performance (our solutions have almost the same management/control interfaces as OVS-DPDK and VPP respectively).  here is a reference on 2017 Nov. DPDK summit (at that time we did a basic integration with clear container) https://www.youtube.com/watch?v=qGdlTW6O2FE
- Start with CNM plugin might be a nature choice without other higher layer module dependency. In a longer term, in a full service mesh deployment (like istio + k8s + Kata), do you have any opinion on CNI plugins? especially speaking of vhost-user support.
