### ISSUE TITLE
stable branch releases should be referenced in user guide

### ISSUE THREAD

**Issue by egernst** [kata-containers/documentation#234]
Need to come up with documentation for stable branch package usage.  Today we only refernce master in the user guide.

**Comment by egernst** [comment]
From Ubuntu as an example:

```
$ sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_$(lsb_release -rs)/ /' > /etc/apt/sources.list.d/kata-containers.list"
$ curl -sL  http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add -
$ sudo -E apt-get update
$ sudo -E apt-get -y install kata-runtime kata-proxy kata-shim
```

In the above, first, we only should say kata-runtime.  That's not the purpose of this discussion though...

Currently we point to master through:
```
http://download.opensuse.org/repositories/home:/katacontainers:/release:$(uname -m)
```
From what I can see, I think going forward we want to be grabbing master from:
```
https://build.opensuse.org/project/show/home:katacontainers:releases:x86_64:master:$(uname -m)
```
I'll need @jcvenegas to confirm this.  Based on this, we'll more easily be able to swap via an environment variable maybe?  For stable, we have: 
```
https://build.opensuse.org/project/show/home:katacontainers:releases:x86_64:stable-1.2:$(uname -m)
https://build.opensuse.org/project/show/home:katacontainers:releases:x86_64:stable-1.1:$(uname -m)
```

I don't want to put a burden on the user for picking an appropriate default, but not sure how to handle this and looking for input.  How to grab "latest stable?"

**Comment by grahamwhaley** [comment]
Good catch. Agree, this all looks like it needs a bit of definition and then update.
The $(arch) addition for sure to fix the new x86 path etc.
It would be great if we could use some sort of symlink-ism, so a download of 'stable-latest' always got you the most recent stable - but my gut tells me maybe we can't generate those paths with OBS?
I have a feeling hard wiring a stable version number in the path then pins them to that version, which is fine if that is the decision they make, but maybe not what we want folks doing by default. It might be that we have to have a 'stable-latest' area and hand link or update that every time we update the most recent stable (and when we add a new stable), so that then tracks the latest stable no matter what.

And then we probably want to decide which 'default install' we promote to end users - do we suggest they run with 'master', or they go with 'stable-latest' by default. I know, it is somewhat situation dependent. My feeling is that we'd recommend going with 'stable-latest'.

**Comment by jodh-intel** [comment]
- We tag all our code repos.
  - We also tag `tests` and `packaging`.
- We're now creating stable branches for our code repos and `tests`.

To cater for this, I think we need to:

- Create stable branches for `packaging` and `documentation`.

That way, when we create a new stable release, we'll "snapshot" both the packaging and the docs. We can then push a PR to the docs repo (and maybe packaging too?) to update the URLs in all the install guides to use the relevant stable URLs (we should be able to automate the creation of those PRs).

@jcvenegas's #170 links nicely to a branch-specific install README which will allow the user to find the right (branch) version of the install docs.

For a user to decide whether to opt for "stable" or "latest", they'll want to know:

- How long "stable" is going to be maintained.
- How they switch to "latest" (and potentially how they switch back).
- What they will be missing (wrt features) by sticking with "stable".

Since the github interface doesn't really allow for this, I think we're going to need a doc somewhere (maybe even just an "official wiki page") that summarises all this along with pointers to *all* the current releases (both in terms of downloadable assets and OBS repos / install docs).

**Comment by egernst** [comment]
James - I'm torn on documentation forking. 
benefits:
keep the architecture document closer to the code (having said that -- look at how quickly and often those docs change).  
cons:
 - I don't want to have to maintain multiple sets of install guides
 - I don't want users to have to suffer through deciding which set of install guides to use.

**Comment by egernst** [comment]
@grahamwhaley:

As a reference, not that it is necessarily how I'd like to do it, but VPP provides some suggested variables: https://wiki.fd.io/view/VPP/Installing_VPP_binaries_from_packages


Symlink-ism would be ideal, as it is written now the paths will even change (master v. stable-1.2 v. stable-1.1).  Perhaps a better naming scheme is necessary too...

**Comment by jodh-intel** [comment]
> James - I'm torn on documentation forking.
> benefits:
> keep the architecture document closer to the code (having said that -- look at how quickly and often those docs change).

The arch doc? Yes, that might change quite a bit and should enforce formal re-review and sign-off on that doc when we cut a release. This is hinted at already here:

- https://github.com/kata-containers/documentation/blob/master/Release-Checklist.md

> cons:
> Need to maintain multiple sets of install guides

True, but the `stable-${version}` docs `should` be almost entirely static. In fact, looking at them, I think the only changes that might be necessary would be to maintain the distro versions the stable release supports (for example, if a particular version of Ubuntu goes EOL whilst a particular stable release hasn't yet :)

Apart from the (I think) compelling snapshot argument about the docs, another advantage in branching is that we will not need to maintain gobs of detail in the latest versions of the docs in `master` about the different stable releases - "master" will simply document "latest", so those docs are kept clean and simple.

But we will need some other "area" to document the menu of options outlining pros+cons of each approach (stable vs. latest) and pointing to specific sets of install guides, etc. As mentioned, that could either be a wiki page, or a formal doc (in master only) in:

- https://github.com/kata-containers/kata-containers

> Users have to decide which set of install guides to use.

But doesn't this just match the decision that users need to make on the version of Kata they will install (stable or "latest"?)

**Comment by egernst** [comment]
maybe ML even - quicker / wider spread of input.

**Comment by jodh-intel** [comment]
@egernst - agreed - http://lists.katacontainers.io/pipermail/kata-dev/2018-September/000465.html.

**Comment by marcov** [comment]
What about an hybrid approach where:
- upon a new release, you just tag the documentation repository with the version number.
- The master branch will include installation instruction for the "latest" and "stable" versions.
- In pages expected to change a lot, like architecture or manuals, you explicitly states that the pages refers to a yet-to-be released version, and point users to the tagged version that matches their installation. E.g. 
> Architecture for [v1.3.0](https://github.com/kata-containers/documentation/blob/v1.3.0/architecture.md), [v1.3.0-rc1](https://github.com/kata-containers/documentation/blob/v1.3.0-rc0/architecture.md), ...

**Comment by marcov** [comment]
In the meanwhile CI nodes are being provisioned with an outdated version of Kata Containers [because of the old links in documentation pages](https://github.com/kata-containers/osbuilder/pull/170#issuecomment-425402956). 

Is it ok to open a PR to fix that while we come to final decision?

**Comment by jodh-intel** [comment]
Absolutely! I guess we should add words to say that users can either select `master` to get the latest, or one of the stable branches listed at: http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/

If you want to raise a PR for the install docs, great! If not, I'll happily do it ;)

**Comment by jodh-intel** [comment]
Obviously, that's an arch-specific URL so we could give that as an example. In fact, the example should currently specify `master` and use either `$(arch)` or `$(uname -m)` also in the bash code block to ensure the CI tests `master` by default (for now atleast).

**Comment by marcov** [comment]
Yeah I'll kickstart a PR.
