### ISSUE TITLE
Create a get started contributor guide

### ISSUE THREAD

**Issue by raravena80** [kata-containers/documentation#247]
Describe all the Kata components with references to the [architecture](https://github.com/kata-containers/documentation/blob/master/architecture.md).

Some of the componets where people can contribute:

- [Documentation](https://github.com/kata-containers/documentation) This repo
- [Runtime](https://github.com/kata-containers/runtime)
   -  List all the subcomponents of runtime somebody can contribute too
- [Agent](https://github.com/kata-containers/agent)
- [Proxy](https://github.com/kata-containers/proxy)
- [Shim](https://github.com/kata-containers/shim)
- [Osbuilder](https://github.com/kata-containers/osbuilder)
- [Tests](https://github.com/kata-containers/tests)
- Any others that I may be missing.

**Comment by jodh-intel** [comment]
Related: #243.

**Comment by jodh-intel** [comment]
Might be neat to have a "high level" diagram (like https://katacontainers.io/static/katacontainers/img/kata-explained1%402x.png) that has hotlinks to very brief details of each component (a few sentences only). Each of those sections would have a "For more details, click here" and that 'here' would link to the full details in the architecture document / dev guide document?

**Comment by grahamwhaley** [comment]
A very quick surf shows that maybe it is possible to get some level of hotlinked pictures rendered on github (you have to read all of the not-too-long thread): https://github.com/asciidoctor/asciidoctor-diagram/issues/166

**Comment by amshinde** [comment]
@jodh-intel Is this still relevant? If so, we need to update the issue to describe what is needed.

**Comment by jodh-intel** [comment]
@amshinde - I would say yes. Although we currently have the following:

- The architecture document (https://github.com/kata-containers/documentation/blob/master/design/architecture.md)
- The contributing guide (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md)
- The developer guide (https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md)

... what we don't have is documentation that explains *to a developer* (at the API / code level) and to an advanced admin (all options, impact of each) how each component works in various ways. I think the original plan was to "flesh out" the following and then promote them to "in-tree" docs when they had stabilised, but that hasn't happened due to other priorities I think:

- https://github.com/kata-containers/documentation/wiki/UserGuide
- https://github.com/kata-containers/community/wiki/Getting-Started-Contributor-Guide

It would probably make sense to create a GitHub project to discuss documentation improvement activities like this. In fact, maybe we could consider a (virtual) "doc sprint" :wink: 

/cc @mvincerx.

**Comment by mvincerx** [comment]
@jodh-intel Please see "Additional information," in this issue:
https://github.com/kata-containers/community/issues/150

I recommend that one top-level landing page caters to **all types** of contributors. 
Otherwise, GitHub documentation will continue to be fragmented and possible frustrate new users who wish to contribute.

I intend for my comments in https://github.com/kata-containers/community/issues/150 to:
- Address this issue (which to me is unresolved);  or 
- Start a New Issue that addresses overall user nav in https://github.com/kata-containers

I want to help solve the issue of "How do different types (roles) of contributors quickly learn where to go to get started?" Let's discuss.
