### ISSUE TITLE
Add Release Process doc

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#32]
We need an equivalent of:

- https://github.com/clearcontainers/runtime/wiki/Release-Process
- https://github.com/clearcontainers/runtime/wiki/Release-Checklist

**Comment by jcvenegas** [comment]
Hopefully most of the process can be automated.

For Clear Containers on a release we 

Automate the process of bump a version ( we dont support beta/alfa versions in the automation).
    - Go to each repo and send a PR to update its version file.
    - This will help to  exercise the CI for the current state of the project.
    - The PR may include release notes by getting information from merged PRs and documented limitations.

After the PR is merged, we tag all the current projects with the new version and include the release notes. 

Some process that may change from Clear Containers.
    -  The image generation: IMO to be published for the release will be created and uploaded as a github release asset in the agent repository.
   - Kernel today the kernel used in Kata CI is installed from Clear Containers packages. 
     We need a default config for the kata kernel. see https://github.com/kata-containers/linux/pull/5
     How will we version the changes for the kata kernel configuration?
     The kernel should build on each PR or we want a precompiled kernel?

**Comment by jcvenegas** [comment]
# Releases 

The kata containers  project follows the semantic [versioning](http://semver.org/).

Versions are in the form `MAJOR.MINOR.PATCH`, examples are: `3.0.0`, `3.0.0-rc.5`, or `99.123.77+foo.bar.baz.5`.

## Release checklist
Change release process, instead create a release candidate we can test the HEAD what will be the last commit using new automated obs package generation we can generate and test commits based on HEAD.

- [ ] Update ```VERSION``` in the runtime repository.
This wil help to tests  the HEAD commit of the master branch using the tests included in the [tests repository][tests].
- [ ] Update the versions of `proxy` and `shim` `agent `.<br/>
  (Note that the "phase" element of the project encoded in the version strings needs to match for all components. For example, when a `beta` is released, the version string for *all* components should show `beta`).
- [ ] Generate OBS packages based on HEAD.
- [ ] Create an **annotated tag** for the new release version (required by `git describe`)
- [ ] Generate OBS packages
  - [ ] Installation tests (must be done for major releases)
    - [ ] Fedora
    - [ ] Ubuntu
    - [ ] Automated tests. 
    - [ ] Integration tests included in the [tests repository][tests] under the integration directory.
- [ ] Write release notes:
  - [ ] Brief summary of known issues, pointing to the appropriate Issues/PRs.
  - [ ] Version of Docker (ideally range of versions, or "up to version X") supported by the release.
  - [ ] cri-o version
  - [ ] cri-containerd version
  - [ ] Version of the OCI spec (ideally range of versions, or "up to version X") supported by the release.
  - [ ] Version of  image used by the release (guest-os-version+agent version).
  - [ ] Add links to Installation instructions.
  - [ ] Document any common vulnerabilities and exposures (CVEs) fixed with links to the CVE database.
- [ ] Check if the [limitations doc](https://github.com/clearcontainers/runtime/blob/master/docs/limitations.md) needs updating.
- [ ] Post release details on the public mailing list.


[tests]: https://github.com/kata-containers/tests

**Comment by jodh-intel** [comment]
Thanks @jcvenegas - I'll add this to the PR...
