### ISSUE TITLE
Create kubernetes installation guides

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#375]
We provide installation guides for Kata with Docker:

- https://github.com/kata-containers/documentation/tree/master/install/docker

... but we don't provide the equivalent for k8s.

Create a set of kubernetes installation guides and update the [kata manager](https://github.com/kata-containers/tests/tree/master/cmd/kata-manager) to support that container manager option.

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/tests/issues/1137.

**Comment by sameo** [comment]
@jodh-intel Both cri-o and containerd should be documented.

**Comment by jodh-intel** [comment]
Hmm, this doesn't look promising:

- https://packages.cloud.google.com/apt/dists

They list:

- xenial (16.04 LTS)
- yakkety (dead)

... but no bionic (18.04 LTS) or newer :cry:

**Comment by jodh-intel** [comment]
Clearly, yakkety should be removed but I'm guessing they package for the lowest common denominator (to make life easier for themselves) since the RPM-based distro URL includes "el7", even for Fedora.

**Comment by chavafg** [comment]
We have this document available: https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#run-kata-containers-with-kubernetes 
although it has links to the cri-o and containerd repos to follow their install guides, so this wont work for the `kata-manager` script.

**Comment by jodh-intel** [comment]
Thanks @chavafg. Yes, we do need to consider if we want to maintain minimal install instructions when there are already official instructions such as:

- https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-using-native-package-management

I'm tempted to say "yes" since:

- It would allow kata-manager to work (meaning we can guarantee our instructions work and also test k8s with kata automatically to some degree).
- I don't *think* the official instructions would need to change much (?)
- the k8s doc web site is extremely comprehensive, but also offers "too many" choices for those starting out with k8s I'd suggest. We can offer an opinionated and simple quickstart solution.

What do others think though?

**Comment by grahamwhaley** [comment]
Resurrecting this then (rather than me open a partial duplicate).
I still think our k8s kata docs need a lot of improvement:

- amalgamate them all into one doc or area (at one point I'm sure I found 5 separate docs, wikis etc.)
- ensure we document all variants we support, containerd, cri-o etc.
  - sure, we should point to their generic installation docs when we can, and then add the kata specific bits to our docs
- Try and tie hand-installation or packaged installation instructions to `kata-deploy` over in the packaging repo - afaict we have two basic installation methods - by hand, or using `kata-deploy`.

@bergwolf @gnawux - somebody said they were planning on cleaning up all the k8s docs - was that either of you? (all I remember is it was not an Intel person...)

k8s is a key platform for kata deploys - we need to make this crystal clear on what the options are and how you go about installing and then configuring them.

@mcastelino @egernst
