### ISSUE TITLE
Question: How to set up vCPU count and memory with docker

### ISSUE THREAD

**Issue by ustiugov** [kata-containers/documentation#464]
Hi,

I need to boot a VM with a particular number of vCPUs and memory, ideally without affecting host OS scheduler. I tried to search for the info how I could do it but could not find anything. Links on Wiki are broken or lead to Docker manuals that talk about cgroup-level CPU constraints and not vCPUs (obviously).

Thank you in advance.

Regards,
Dmitrii

**Comment by caoruidong** [comment]
You can edit it in configuration.toml. Probably under /usr/share/defaults/kata-containers/

**Comment by grahamwhaley** [comment]
Hi @ustiugov - thanks for reporting. If you have pointers to those broken links then we can go fix them (or, if you PR fixes, that would be excellent ;-) ).

The number of vCPUs and memory passed to your kata container VM should honour the requests passed down from your orchestrator, or use the defaults. I see @caoruidong has just mentioned where the defaults for Kata are set - the file has comments that should explain.
Otherwise, for `docker`, you can use the `--cpus` and `--memory` type command line options to configure. For `kubernetes`, you can set resources in the `.yaml` files where you construct the pod etc.

**Comment by ustiugov** [comment]
Hi @grahamwhaley @caoruidong, thank you very much for the prompt response. 

These commands work as expected (from the perspective of the guest). However, my concern is that these Docker commands configure the behavior of the host scheduler (for conventional containers). For example, `--cpus` define the scheduler quota (e.g., 0.5 or 1 CPU for that particular container on the host). 
In the case of kata containers, are there any implications of these commands for the host or it's just for the guest (e.g., the number of vCPUs and memory of the VM)?

Thank you in advance.

**Comment by grahamwhaley** [comment]
Good question @ustiugov ;-)  I'm going to rope in @jcvenegas @devimc and @egernst to see if they have more intimate knowledge.

**Comment by ustiugov** [comment]
Thank you, I greatly appreciate that. 
Regarding the broken links. For example, this one (pointing to CPU constraints) on [Developer's guide page](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md).
The same broken link is on the [wiki Home page](https://github.com/kata-containers/documentation/wiki).

**Comment by jodh-intel** [comment]
Hi @ustiugov - I've fixed the wiki link, but I don't see a broken link in the dev guide?

**Comment by ustiugov** [comment]
Sorry, my bad, here is the [link](https://github.com/kata-containers/documentation/wiki/UserGuide#cpus) and it is in UserGuide. Thank you!

**Comment by devimc** [comment]
link to `cpu constraints document` is broken, fixing it...

**Comment by grahamwhaley** [comment]
Ah, the userguide ;-) Yeah, that is an in-flight work in progress.... that anybody can fix (in theory) - it is a wiki after all ;-) thx @devimc ;-)

**Comment by jodh-intel** [comment]
Thanks for letting us know @ustiugov.

ftr, all URLs and all markdown links are now validated by our CI (tal at https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L356 and https://github.com/kata-containers/tests/tree/master/cmd/check-markdown if you're curious).

However, we don't have that validation on the wikis. That is an interesting idea though since they are of course "just git repos" too. Maybe once zuul is fully operational @grahamwhaley we can run a daily job to `git clone` all the wikis and run the doc checks on them too?

**Comment by grahamwhaley** [comment]
We probably have enough `Zuul` infra in place to try and do that already - the bit I'm trying to fix now is to run an actual kata container - which, we should not need to do for this static link check...
Might be an interesting way for me to figure out a couple of other things in Zuul I've not cracked yet:
- how to do timed regular runs (rather than github triggered for instance)
- how/where to send results, like emailing to an MTA :-), which I gather there should be facility for, so we can send the report to one of the lists (or, I guess, maybe slack... if we can have a secret key store for instance).

**Comment by grahamwhaley** [comment]
oh, and @egernst I expect to suggest we could use Google Actions, which is also probably a perfectly valid route as well.

**Comment by grahamwhaley** [comment]
s/Google/Github/

**Comment by egernst** [comment]
@ustiugov - are your questions clarified at this point?

**Comment by ustiugov** [comment]
@egernst yes, thank you. I think this issue can be closed.
