### ISSUE TITLE
Fedora 27 install

### ISSUE THREAD

**Issue by gabibeyer** [kata-containers/documentation#528]
The install docs/table state that Fedora 27 can be automatically installed, however Fedora_27 no longer exists on the openSUSE download server: http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/

Should we update documentation to either remove Fedora 27 support or modify the link to be `stable-1.3` instead of `master`. Or, try and return the repo back to the download server master dir?

**Comment by chavafg** [comment]
I think we should remove Fedora 27 as it is no longer supported and add Fedora 30 instead.

**Comment by grahamwhaley** [comment]
ack, as we all probably know, the [Fedora support/release cycle](https://fedoraproject.org/wiki/Fedora_Release_Life_Cycle) gives ~13months support per release, and releases every 6 months - so we have two valid versions to support/test at any point in time.
It looks like Fedora30 was released at the end of April, so I suspect we should currently be supporting/testing F30/F29 - and, I would guess F31 is not that far away..
Yes, tracking the rolling releases of Fedora will be an on-going overhead of Kata maintenance..

**Comment by ganeshmaharaj** [comment]
I guess we cannot just say <latest> and <latest - 1> can we? 😜

**Comment by jodh-intel** [comment]
@ganeshmaharaj - I like avoiding hard-coded numbers in docs. However, I think that although it's more work for us, it's better if we specify actual version numbers since:

- It ensures we re-test with the new releases.
- There is no confusion for users: we specify precisely which versions Kata can be installed with.
- It avoids a bad experience when, say, Fedora `n+1` gets released and users attempt to install Kata before we've created packages for that release.
