### ISSUE TITLE
Xen or ACRN support?

### ISSUE THREAD

**Issue by deitch** [kata-containers/documentation#566]
Are there plans to support additional hypervisors like Xen or ACRN? The docs [here](https://github.com/kata-containers/documentation/blob/master/design/architecture.md#hypervisor) say 

> Kata Containers is designed to support multiple hypervisors. For the 1.0 release, Kata Containers uses just QEMU/KVM to create virtual machines where containers will run

And the firecracker work indicates that it is pluggable. Granted, Xen and ACRN assume a level of kernel support (actually, booting, since they are type 1 hypervisors), but assuming those are in place, is it possible to get them worked in, and are there plans (or at least "guide to adding a hypervisor")?

**Comment by jodh-intel** [comment]
Hi @deitch. That doc is correct but needs a refresh (https://github.com/kata-containers/documentation/issues/567 raised) since newer releases support additional hypervisors: QEMU, NEMU, ACRN and Firecracker. See:

- https://github.com/kata-containers/runtime/tree/master/cli/config
- https://github.com/kata-containers/runtime/releases

Regarding Xen, it might be possible to add support if there is interest (would you be interested in contributing?)

Finally, there is documentation on how to add support for a new hypervisor in the form of the virtcontainers API documentation:

- https://github.com/kata-containers/runtime/blob/master/virtcontainers/README.md

**Comment by deitch** [comment]
That is great! 

I might be. I am doing some work with the fine folks at [lf-edge eve](https://github.com/lf-edge/eve). The current base is running pure VMs (i.e. real OSes), not OCI containers, but are experimenting with getting proper OCI containers running while fully isolated by a VM (sound familiar? :-) ). The current hypervisor is Xen, although ACRN support was just merged in courtesy of one of your Intel folks.

So... I think there very well might be interest. I would be happy to do it, but need to see where the priorities are first; IMO I think it is coming fast. They did a quick rkt proof-of-concept, largely because rkt-xen support was there and ready, but obviously rkt is archived and OCI compatibility is the way to go.

I am going to circle back and see timelines and how we can get some love in this direction.

**Comment by jodh-intel** [comment]
Hi @deitch - this sounds great! :smile:

Please do let us know how this progresses (either here, or mailing list, etc - see https://github.com/kata-containers/community#join-us).

**Comment by deitch** [comment]
Will do. I sent you an email to your work address as well.

**Comment by edwinbalani** [comment]
I've been watching this issue silently.  Has it been closed because Xen/ACRN support is now added, or is the work abandoned or obsoleted?
